//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Win_Auth_Login_Client.wcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfService.iWCF")]
    public interface iWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/iInfo", ReplyAction="http://tempuri.org/iWCF/iInfoResponse")]
        void iInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/iInfo", ReplyAction="http://tempuri.org/iWCF/iInfoResponse")]
        System.Threading.Tasks.Task iInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/jInfo", ReplyAction="http://tempuri.org/iWCF/jInfoResponse")]
        string jInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/jInfo", ReplyAction="http://tempuri.org/iWCF/jInfoResponse")]
        System.Threading.Tasks.Task<string> jInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/GetIP", ReplyAction="http://tempuri.org/iWCF/GetIPResponse")]
        string GetIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/GetIP", ReplyAction="http://tempuri.org/iWCF/GetIPResponse")]
        System.Threading.Tasks.Task<string> GetIPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/GetIP2", ReplyAction="http://tempuri.org/iWCF/GetIP2Response")]
        string GetIP2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/GetIP2", ReplyAction="http://tempuri.org/iWCF/GetIP2Response")]
        System.Threading.Tasks.Task<string> GetIP2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iWCFChannel : WCF_Win_Auth_Login_Client.wcfService.iWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iWCFClient : System.ServiceModel.ClientBase<WCF_Win_Auth_Login_Client.wcfService.iWCF>, WCF_Win_Auth_Login_Client.wcfService.iWCF {
        
        public iWCFClient() {
        }
        
        public iWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void iInfo() {
            base.Channel.iInfo();
        }
        
        public System.Threading.Tasks.Task iInfoAsync() {
            return base.Channel.iInfoAsync();
        }
        
        public string jInfo() {
            return base.Channel.jInfo();
        }
        
        public System.Threading.Tasks.Task<string> jInfoAsync() {
            return base.Channel.jInfoAsync();
        }
        
        public string GetIP() {
            return base.Channel.GetIP();
        }
        
        public System.Threading.Tasks.Task<string> GetIPAsync() {
            return base.Channel.GetIPAsync();
        }
        
        public string GetIP2() {
            return base.Channel.GetIP2();
        }
        
        public System.Threading.Tasks.Task<string> GetIP2Async() {
            return base.Channel.GetIP2Async();
        }
    }
}
