CREATE PROCEDURE Proc
AS
	SET XACT_ABORT ON;
	BEGIN TRY
		BEGIN TRANSACTION
			-- DO some work
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF XACT_STATE() <> 0
			ROLLBACK;
		DECLARE @ErrorMessage NVARCHAR(255)
		SET @ErrorMessage = CONCAT(N'Error',ERROR_NUMBER(),ERROR_MESSAGE());
		THROW 50001, @ErrorMessage,1;
	END CATCH