//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.ServerRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerRef.IXServer")]
    public interface IXServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXServer/Divide", ReplyAction="http://tempuri.org/IXServer/DivideResponse")]
        int Divide(int val1, int val2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXServer/Divide", ReplyAction="http://tempuri.org/IXServer/DivideResponse")]
        System.Threading.Tasks.Task<int> DivideAsync(int val1, int val2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXServerChannel : WCFClient.ServerRef.IXServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XServerClient : System.ServiceModel.ClientBase<WCFClient.ServerRef.IXServer>, WCFClient.ServerRef.IXServer {
        
        public XServerClient() {
        }
        
        public XServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Divide(int val1, int val2) {
            return base.Channel.Divide(val1, val2);
        }
        
        public System.Threading.Tasks.Task<int> DivideAsync(int val1, int val2) {
            return base.Channel.DivideAsync(val1, val2);
        }
    }
}
